export type Domain = 'engineering' | 'engineering-team' | 'ai-research' | 'ai-security' | 'research' | 'research-ops'

export interface Skill {
  name: string
  description: string
  descriptionPt: string
  tags: string[]
  domain: Domain
  icon: string
  isNew?: boolean
}

export const domains: { id: Domain; label: string; count: number; color: string }[] = [
  { id: 'engineering', label: 'Engineering', count: 37, color: 'cyan' },
  { id: 'engineering-team', label: 'Engineering Team', count: 38, color: 'blue' },
  { id: 'ai-research', label: 'AI Research', count: 2, color: 'violet' },
  { id: 'ai-security', label: 'AI Security', count: 1, color: 'rose' },
  { id: 'research', label: 'Research', count: 8, color: 'amber' },
  { id: 'research-ops', label: 'Research Ops', count: 5, color: 'emerald' },
]

export const skills: Skill[] = [
  // ── Engineering ──────────────────────────────────────────
  {
    name: 'code-review',
    description: 'Multi-severity analysis covering security, correctness, performance, and maintainability. Returns a score and merge verdict.',
    descriptionPt: 'Análise multi-severidade cobrindo segurança, correção, performance e manutenibilidade. Retorna pontuação e veredicto de merge.',
    tags: ['security', 'performance', 'score/10'],
    domain: 'engineering',
    icon: '🔍',
  },
  {
    name: 'debug-error',
    description: 'Identifies root cause from stack traces — not just the symptom. Provides fix, verification steps, and prevention strategy.',
    descriptionPt: 'Identifica a causa raiz a partir de stack traces — não apenas o sintoma. Fornece correção, etapas de verificação e estratégia de prevenção.',
    tags: ['root-cause', 'stack-trace', 'prevention'],
    domain: 'engineering',
    icon: '🐛',
  },
  {
    name: 'explain-code',
    description: 'Depth-adjustable explanations: beginner (analogies), intermediate (design decisions), or expert (nuances & trade-offs).',
    descriptionPt: 'Explicações com profundidade ajustável: iniciante (analogias), intermediário (decisões de design) ou especialista (nuances e trade-offs).',
    tags: ['beginner', 'intermediate', 'expert'],
    domain: 'engineering',
    icon: '💡',
  },
  {
    name: 'generate-tests',
    description: 'Complete unit tests with AAA structure for Jest, Vitest, Pytest, and Go. Happy path, edge cases, and full coverage modes.',
    descriptionPt: 'Testes unitários completos com estrutura AAA para Jest, Vitest, Pytest e Go. Caminho feliz, casos extremos e modos de cobertura total.',
    tags: ['jest', 'vitest', 'pytest', 'go'],
    domain: 'engineering',
    icon: '🧪',
  },
  {
    name: 'git-commit',
    description: 'Generates 3 Conventional Commit options from diffs — minimal, scoped, or with body. Flags mixed commits to split.',
    descriptionPt: 'Gera 3 opções de Conventional Commit a partir de diffs — mínimo, com escopo ou com corpo. Sinaliza commits mistos para divisão.',
    tags: ['conventional', '3 options'],
    domain: 'engineering',
    icon: '📝',
  },
  {
    name: 'refactor',
    description: 'Clean Code, SOLID, DRY, or Performance modes. Never silently changes behavior — explains every decision.',
    descriptionPt: 'Modos Clean Code, SOLID, DRY ou Performance. Nunca altera comportamento silenciosamente — explica cada decisão.',
    tags: ['clean-code', 'solid', 'dry', 'perf'],
    domain: 'engineering',
    icon: '♻️',
  },
  {
    name: 'write-docs',
    description: 'JSDoc, TSDoc, Python docstrings (Google style), and strategic inline comments. Explains the why, not just the what.',
    descriptionPt: 'JSDoc, TSDoc, docstrings Python (estilo Google) e comentários inline estratégicos. Explica o porquê, não apenas o quê.',
    tags: ['jsdoc', 'tsdoc', 'python'],
    domain: 'engineering',
    icon: '📖',
  },
  {
    name: 'llm-cost-optimizer',
    description: 'Analyzes LLM inference costs and proposes optimizations: model selection, prompt compression, caching, and batching.',
    descriptionPt: 'Analisa custos de inferência LLM e propõe otimizações: seleção de modelo, compressão de prompt, cache e batching.',
    tags: ['cost', 'caching', 'batching'],
    domain: 'engineering',
    icon: '💰',
    isNew: true,
  },
  {
    name: 'prompt-engineering',
    description: 'Designs, evaluates, and iterates on LLM prompts — system prompts, few-shot examples, chain-of-thought, and structured outputs.',
    descriptionPt: 'Projeta, avalia e itera sobre prompts LLM — prompts de sistema, exemplos few-shot, chain-of-thought e saídas estruturadas.',
    tags: ['system-prompt', 'few-shot', 'CoT'],
    domain: 'engineering',
    icon: '✍️',
    isNew: true,
  },
  {
    name: 'agent-designer',
    description: 'Designs AI agent architectures: tool selection, memory systems, multi-agent patterns, control flow, and production hardening.',
    descriptionPt: 'Projeta arquiteturas de agentes IA: seleção de ferramentas, sistemas de memória, padrões multi-agente, fluxo de controle e hardening em produção.',
    tags: ['ReAct', 'tool-use', 'multi-agent'],
    domain: 'engineering',
    icon: '🤖',
    isNew: true,
  },
  {
    name: 'agenthub',
    description: 'Multi-agent collaboration framework — spawns N parallel subagents competing on the same task via git worktree isolation.',
    descriptionPt: 'Framework de colaboração multi-agente — cria N subagentes paralelos competindo na mesma tarefa via isolamento git worktree.',
    tags: ['parallel', 'worktree', 'orchestration'],
    domain: 'engineering',
    icon: '🕸️',
  },
  {
    name: 'autoresearch-agent',
    description: 'Autonomous experiment loop that optimizes any file by a measurable metric — inspired by Karpathy\'s autoresearch.',
    descriptionPt: 'Loop de experimento autônomo que otimiza qualquer arquivo por uma métrica mensurável — inspirado no autoresearch de Karpathy.',
    tags: ['autonomous', 'optimization', 'karpathy'],
    domain: 'engineering',
    icon: '🔬',
  },
  {
    name: 'chaos-engineering',
    description: 'Plan, run, and learn from chaos engineering experiments. Hypothesis-driven resilience testing for production systems.',
    descriptionPt: 'Planeje, execute e aprenda com experimentos de engenharia de caos. Teste de resiliência orientado por hipóteses para sistemas em produção.',
    tags: ['resilience', 'hypothesis', 'production'],
    domain: 'engineering',
    icon: '⚡',
  },
  {
    name: 'docker-development',
    description: 'Docker containerization patterns, multi-stage builds, compose orchestration, and production-ready image optimization.',
    descriptionPt: 'Padrões de containerização Docker, builds multi-stage, orquestração com compose e otimização de imagens para produção.',
    tags: ['docker', 'compose', 'containers'],
    domain: 'engineering',
    icon: '🐳',
  },
  {
    name: 'kubernetes-operator',
    description: 'CRD validator, reconcile linter, and capability auditor for Kubernetes operator development.',
    descriptionPt: 'Validador de CRD, linter de reconcile e auditor de capacidades para desenvolvimento de operadores Kubernetes.',
    tags: ['k8s', 'crd', 'operator'],
    domain: 'engineering',
    icon: '⚙️',
  },
  {
    name: 'terraform-patterns',
    description: 'Terraform infrastructure-as-code patterns, module design, state management, and security best practices.',
    descriptionPt: 'Padrões de infraestrutura-como-código com Terraform, design de módulos, gerenciamento de estado e boas práticas de segurança.',
    tags: ['terraform', 'iac', 'modules'],
    domain: 'engineering',
    icon: '🏗️',
  },
  {
    name: 'helm-chart-builder',
    description: 'Kubernetes Helm chart generation, templating patterns, and values management for production deployments.',
    descriptionPt: 'Geração de Helm charts para Kubernetes, padrões de templating e gerenciamento de values para deploys em produção.',
    tags: ['helm', 'k8s', 'charts'],
    domain: 'engineering',
    icon: '📦',
  },
  {
    name: 'slo-architect',
    description: 'SLO/SLI/error-budget discipline per Google SRE Workbook. Defines reliability targets and alerting strategies.',
    descriptionPt: 'Disciplina SLO/SLI/error-budget conforme o Google SRE Workbook. Define metas de confiabilidade e estratégias de alertas.',
    tags: ['slo', 'sli', 'sre', 'error-budget'],
    domain: 'engineering',
    icon: '📊',
  },
  {
    name: 'karpathy-coder',
    description: 'Karpathy-aligned coding practices: assumption audits, complexity checks, diff surgery, and minimal footprint.',
    descriptionPt: 'Práticas de código alinhadas ao estilo Karpathy: auditorias de suposições, verificações de complexidade, cirurgia de diff e pegada mínima.',
    tags: ['minimal', 'assumptions', 'complexity'],
    domain: 'engineering',
    icon: '🧠',
  },
  {
    name: 'llm-wiki',
    description: 'Persistent markdown knowledge vault using Karpathy\'s LLM wiki pattern — structured, searchable, and evolving.',
    descriptionPt: 'Cofre de conhecimento markdown persistente usando o padrão LLM wiki de Karpathy — estruturado, pesquisável e evolutivo.',
    tags: ['knowledge', 'vault', 'markdown'],
    domain: 'engineering',
    icon: '📚',
  },
  {
    name: 'workflow-builder',
    description: 'Design and implement AI-powered workflow orchestration — task routing, retry logic, and state management.',
    descriptionPt: 'Projete e implemente orquestração de workflow com IA — roteamento de tarefas, lógica de retry e gerenciamento de estado.',
    tags: ['workflow', 'orchestration', 'state'],
    domain: 'engineering',
    icon: '🔄',
  },
  {
    name: 'prompt-governance',
    description: 'Prompt governance framework: versioning, consistency audits, drift detection, and team alignment.',
    descriptionPt: 'Framework de governança de prompts: versionamento, auditorias de consistência, detecção de drift e alinhamento de equipe.',
    tags: ['governance', 'versioning', 'consistency'],
    domain: 'engineering',
    icon: '📋',
  },
  {
    name: 'security-guidance',
    description: 'PreToolUse security reminder hook with 12 pattern detection — injection, secrets, path traversal, and more.',
    descriptionPt: 'Hook de lembrete de segurança PreToolUse com detecção de 12 padrões — injeção, secrets, path traversal e mais.',
    tags: ['security', 'hook', 'patterns'],
    domain: 'engineering',
    icon: '🛡️',
  },
  {
    name: 'feature-flags-architect',
    description: 'Feature flag debt scanner, rollout planner, and kill-switch audit. LaunchDarkly, Unleash, and custom implementations.',
    descriptionPt: 'Scanner de dívida de feature flags, planejador de rollout e auditoria de kill-switch. LaunchDarkly, Unleash e implementações customizadas.',
    tags: ['feature-flags', 'rollout', 'audit'],
    domain: 'engineering',
    icon: '🚩',
  },
  {
    name: 'statistical-analyst',
    description: 'Statistical analysis, hypothesis testing, A/B test design, and significance interpretation for engineers.',
    descriptionPt: 'Análise estatística, testes de hipótese, design de testes A/B e interpretação de significância para engenheiros.',
    tags: ['stats', 'a/b', 'hypothesis'],
    domain: 'engineering',
    icon: '📈',
  },
  {
    name: 'data-quality-auditor',
    description: 'Audit datasets for completeness, consistency, accuracy, and schema conformance with actionable fixes.',
    descriptionPt: 'Audita datasets para completude, consistência, precisão e conformidade de schema com correções acionáveis.',
    tags: ['data', 'quality', 'audit'],
    domain: 'engineering',
    icon: '🔎',
  },
  {
    name: 'universal-scraping-architect',
    description: 'Web scraping architecture with anti-detection patterns, JS rendering, rate limiting, and proxy rotation.',
    descriptionPt: 'Arquitetura de web scraping com padrões anti-detecção, renderização JS, limitação de taxa e rotação de proxies.',
    tags: ['scraping', 'automation', 'playwright'],
    domain: 'engineering',
    icon: '🕷️',
  },
  {
    name: 'write-a-skill',
    description: 'Meta-skill for writing new skills following the 10-Pattern Framework — the fastest way to extend this library.',
    descriptionPt: 'Meta-skill para escrever novas skills seguindo o Framework de 10 Padrões — a forma mais rápida de estender esta biblioteca.',
    tags: ['meta', '10-patterns', 'authoring'],
    domain: 'engineering',
    icon: '✏️',
  },
  {
    name: 'code-tour',
    description: 'Create CodeTour .tour files for persona-targeted code walkthroughs — onboarding, architecture, and debugging tours.',
    descriptionPt: 'Cria arquivos .tour do CodeTour para walkthroughs de código por persona — tours de onboarding, arquitetura e debugging.',
    tags: ['codetour', 'onboarding', 'docs'],
    domain: 'engineering',
    icon: '🗺️',
  },
  {
    name: 'caveman',
    description: 'Ultra-compressed communication mode (~75% token reduction). Speaks in short bursts, no filler, pure signal.',
    descriptionPt: 'Modo de comunicação ultra-comprimido (~75% de redução de tokens). Fala em rajadas curtas, sem rodeios, sinal puro.',
    tags: ['tokens', 'compression', 'brevity'],
    domain: 'engineering',
    icon: '🪨',
  },
  {
    name: 'handoff',
    description: 'Conversation-continuity generator with structured 5-emphasis template for seamless context handoffs.',
    descriptionPt: 'Gerador de continuidade de conversa com template estruturado de 5 ênfases para handoffs de contexto sem interrupções.',
    tags: ['handoff', 'context', 'continuity'],
    domain: 'engineering',
    icon: '🤝',
  },
  {
    name: 'grill-me',
    description: 'Relentless plan-interrogator with 3 stdlib tools — stress-tests assumptions before you build anything.',
    descriptionPt: 'Interrogador implacável de planos com 3 ferramentas stdlib — testa suposições sob pressão antes de você construir qualquer coisa.',
    tags: ['interrogation', 'assumptions', 'planning'],
    domain: 'engineering',
    icon: '🔥',
  },
  // Engineering (skills subfolder) — top picks
  {
    name: 'rag-architect',
    description: 'Retrieval-Augmented Generation architecture: chunking strategies, embedding models, re-ranking, and eval.',
    descriptionPt: 'Arquitetura de Geração com Recuperação Aumentada: estratégias de chunking, modelos de embedding, re-ranking e avaliação.',
    tags: ['rag', 'embeddings', 'retrieval'],
    domain: 'engineering',
    icon: '🗂️',
    isNew: true,
  },
  {
    name: 'ship-gate',
    description: 'Pre-production audit with 89 checks across 8 categories — security, perf, observability, and reliability.',
    descriptionPt: 'Auditoria pré-produção com 89 verificações em 8 categorias — segurança, performance, observabilidade e confiabilidade.',
    tags: ['pre-prod', 'audit', '89 checks'],
    domain: 'engineering',
    icon: '🚢',
  },
  {
    name: 'observability-designer',
    description: 'Design observability stacks: tracing, metrics, logging, and alerting with OpenTelemetry and modern tooling.',
    descriptionPt: 'Projeta stacks de observabilidade: tracing, métricas, logging e alertas com OpenTelemetry e ferramentas modernas.',
    tags: ['otel', 'tracing', 'metrics'],
    domain: 'engineering',
    icon: '👁️',
  },
  {
    name: 'performance-profiler',
    description: 'Identify and eliminate performance bottlenecks: CPU, memory, I/O, and network with actionable optimizations.',
    descriptionPt: 'Identifica e elimina gargalos de performance: CPU, memória, I/O e rede com otimizações acionáveis.',
    tags: ['profiling', 'perf', 'optimization'],
    domain: 'engineering',
    icon: '⏱️',
  },
  {
    name: 'mcp-server-builder',
    description: 'Build, test, and publish Model Context Protocol servers — tools, resources, prompts, and sampling.',
    descriptionPt: 'Cria, testa e publica servidores Model Context Protocol — ferramentas, recursos, prompts e sampling.',
    tags: ['mcp', 'tools', 'protocol'],
    domain: 'engineering',
    icon: '🔌',
    isNew: true,
  },

  // ── Engineering Team ──────────────────────────────────────
  {
    name: 'ai-security',
    description: 'AI/ML system security assessment — prompt injection, jailbreak detection, model inversion, and data poisoning.',
    descriptionPt: 'Avaliação de segurança de sistemas AI/ML — injeção de prompt, detecção de jailbreak, inversão de modelo e envenenamento de dados.',
    tags: ['llm-sec', 'injection', 'jailbreak'],
    domain: 'engineering-team',
    icon: '🔐',
    isNew: true,
  },
  {
    name: 'cloud-security',
    description: 'Cloud infrastructure security posture assessment for AWS, GCP, and Azure. IAM, network, and compliance.',
    descriptionPt: 'Avaliação de postura de segurança de infraestrutura em nuvem para AWS, GCP e Azure. IAM, rede e conformidade.',
    tags: ['cloud', 'iam', 'posture'],
    domain: 'engineering-team',
    icon: '☁️',
  },
  {
    name: 'red-team',
    description: 'Red team methodology and MITRE ATT&CK kill-chain planning for authorized security assessments.',
    descriptionPt: 'Metodologia de red team e planejamento de kill-chain MITRE ATT&CK para avaliações de segurança autorizadas.',
    tags: ['red-team', 'mitre', 'pentest'],
    domain: 'engineering-team',
    icon: '🎯',
  },
  {
    name: 'security-pen-testing',
    description: 'Penetration testing methodology: recon, exploitation, post-exploitation, and professional reporting.',
    descriptionPt: 'Metodologia de teste de penetração: reconhecimento, exploração, pós-exploração e relatório profissional.',
    tags: ['pentest', 'exploit', 'reporting'],
    domain: 'engineering-team',
    icon: '🗡️',
  },
  {
    name: 'incident-response',
    description: 'SEV1-SEV4 incident triage, runbook execution, postmortem writing, and blameless culture facilitation.',
    descriptionPt: 'Triagem de incidentes SEV1-SEV4, execução de runbook, escrita de postmortem e facilitação de cultura sem culpa.',
    tags: ['incident', 'sev1', 'postmortem'],
    domain: 'engineering-team',
    icon: '🚨',
  },
  {
    name: 'threat-detection',
    description: 'Hypothesis-driven threat hunting with MITRE ATT&CK mapping and detection rule authoring.',
    descriptionPt: 'Caça a ameaças orientada por hipóteses com mapeamento MITRE ATT&CK e criação de regras de detecção.',
    tags: ['hunting', 'detection', 'mitre'],
    domain: 'engineering-team',
    icon: '🔭',
  },
  {
    name: 'playwright-pro',
    description: 'Production-grade Playwright testing: generation, fixing flaky tests, BrowserStack, coverage, and reporting.',
    descriptionPt: 'Testes Playwright de nível produção: geração, correção de testes instáveis, BrowserStack, cobertura e relatórios.',
    tags: ['playwright', 'e2e', 'testing'],
    domain: 'engineering-team',
    icon: '🎭',
  },
  {
    name: 'a11y-audit',
    description: 'WCAG 2.2 accessibility audit and remediation for React, Next.js, Vue, Angular, Svelte, and HTML.',
    descriptionPt: 'Auditoria e remediação de acessibilidade WCAG 2.2 para React, Next.js, Vue, Angular, Svelte e HTML.',
    tags: ['wcag', 'a11y', 'react'],
    domain: 'engineering-team',
    icon: '♿',
  },
  {
    name: 'tdd-guide',
    description: 'Test-driven development guide: red-green-refactor discipline, test pyramid, and CI integration patterns.',
    descriptionPt: 'Guia de desenvolvimento orientado a testes: disciplina red-green-refactor, pirâmide de testes e padrões de integração CI.',
    tags: ['tdd', 'red-green', 'ci'],
    domain: 'engineering-team',
    icon: '✅',
  },
  {
    name: 'adversarial-reviewer',
    description: 'Adversarial code review with hostile reviewer personas — finds what friendly reviewers miss.',
    descriptionPt: 'Revisão de código adversarial com personas de revisor hostil — encontra o que revisores amigáveis perdem.',
    tags: ['adversarial', 'review', 'hostile'],
    domain: 'engineering-team',
    icon: '😈',
  },
  {
    name: 'senior-fullstack',
    description: 'Senior fullstack engineering patterns: architecture decisions, API design, state management, and deployment.',
    descriptionPt: 'Padrões de engenharia fullstack sênior: decisões de arquitetura, design de API, gerenciamento de estado e deploy.',
    tags: ['fullstack', 'architecture', 'api'],
    domain: 'engineering-team',
    icon: '🧑‍💻',
  },
  {
    name: 'senior-backend',
    description: 'Senior backend engineering: distributed systems, database design, caching, queues, and reliability.',
    descriptionPt: 'Engenharia backend sênior: sistemas distribuídos, design de banco de dados, cache, filas e confiabilidade.',
    tags: ['backend', 'distributed', 'reliability'],
    domain: 'engineering-team',
    icon: '⚙️',
  },
  {
    name: 'senior-frontend',
    description: 'Senior frontend engineering: performance, accessibility, component architecture, and modern tooling.',
    descriptionPt: 'Engenharia frontend sênior: performance, acessibilidade, arquitetura de componentes e ferramentas modernas.',
    tags: ['frontend', 'performance', 'react'],
    domain: 'engineering-team',
    icon: '🎨',
  },
  {
    name: 'senior-devops',
    description: 'Senior DevOps: CI/CD pipelines, infrastructure as code, platform engineering, and SRE practices.',
    descriptionPt: 'DevOps sênior: pipelines CI/CD, infraestrutura como código, engenharia de plataforma e práticas SRE.',
    tags: ['devops', 'ci-cd', 'platform'],
    domain: 'engineering-team',
    icon: '🔧',
  },
  {
    name: 'senior-ml-engineer',
    description: 'Senior ML engineering: model deployment, MLOps, feature stores, experiment tracking, and serving.',
    descriptionPt: 'Engenharia ML sênior: deploy de modelos, MLOps, feature stores, rastreamento de experimentos e serving.',
    tags: ['mlops', 'deployment', 'serving'],
    domain: 'engineering-team',
    icon: '🤖',
  },
  {
    name: 'senior-data-engineer',
    description: 'Senior data engineering: pipeline design, data modeling, orchestration (Airflow/Prefect), and quality.',
    descriptionPt: 'Engenharia de dados sênior: design de pipelines, modelagem de dados, orquestração (Airflow/Prefect) e qualidade.',
    tags: ['data-eng', 'pipelines', 'airflow'],
    domain: 'engineering-team',
    icon: '🗄️',
  },
  {
    name: 'senior-data-scientist',
    description: 'Senior data science: EDA, feature engineering, model selection, validation, and business communication.',
    descriptionPt: 'Ciência de dados sênior: EDA, engenharia de features, seleção de modelos, validação e comunicação com o negócio.',
    tags: ['data-science', 'eda', 'modeling'],
    domain: 'engineering-team',
    icon: '📊',
  },
  {
    name: 'senior-qa',
    description: 'Senior QA engineering: test strategy, risk-based testing, automation frameworks, and quality gates.',
    descriptionPt: 'Engenharia QA sênior: estratégia de testes, testes baseados em risco, frameworks de automação e quality gates.',
    tags: ['qa', 'test-strategy', 'automation'],
    domain: 'engineering-team',
    icon: '🔬',
  },
  {
    name: 'aws-solution-architect',
    description: 'AWS infrastructure architecture: VPC design, ECS/EKS, Lambda, RDS, and Well-Architected Framework.',
    descriptionPt: 'Arquitetura de infraestrutura AWS: design de VPC, ECS/EKS, Lambda, RDS e Well-Architected Framework.',
    tags: ['aws', 'vpc', 'well-architected'],
    domain: 'engineering-team',
    icon: '☁️',
  },
  {
    name: 'gcp-cloud-architect',
    description: 'GCP cloud architecture: GKE, Cloud Run, BigQuery, Pub/Sub, and Terraform patterns.',
    descriptionPt: 'Arquitetura de nuvem GCP: GKE, Cloud Run, BigQuery, Pub/Sub e padrões Terraform.',
    tags: ['gcp', 'gke', 'bigquery'],
    domain: 'engineering-team',
    icon: '🌐',
  },
  {
    name: 'azure-cloud-architect',
    description: 'Azure cloud architecture: AKS, Functions, CosmosDB, and ARM/Bicep infrastructure templates.',
    descriptionPt: 'Arquitetura de nuvem Azure: AKS, Functions, CosmosDB e templates de infraestrutura ARM/Bicep.',
    tags: ['azure', 'aks', 'bicep'],
    domain: 'engineering-team',
    icon: '💙',
  },
  {
    name: 'senior-secops',
    description: 'Senior security operations: SOC workflows, alert triage, SIEM correlation, and playbook automation.',
    descriptionPt: 'Operações de segurança sênior: workflows SOC, triagem de alertas, correlação SIEM e automação de playbook.',
    tags: ['soc', 'siem', 'triage'],
    domain: 'engineering-team',
    icon: '🛡️',
  },
  {
    name: 'senior-security',
    description: 'Senior security engineering: secure SDLC, threat modeling, OWASP top 10, and security architecture.',
    descriptionPt: 'Engenharia de segurança sênior: SDLC seguro, modelagem de ameaças, OWASP top 10 e arquitetura de segurança.',
    tags: ['sdlc', 'owasp', 'threat-modeling'],
    domain: 'engineering-team',
    icon: '🔒',
  },
  {
    name: 'stripe-integration-expert',
    description: 'Stripe payment integration: subscriptions, webhooks, checkout, Connect, and compliance patterns.',
    descriptionPt: 'Integração de pagamentos Stripe: assinaturas, webhooks, checkout, Connect e padrões de conformidade.',
    tags: ['stripe', 'payments', 'webhooks'],
    domain: 'engineering-team',
    icon: '💳',
  },
  {
    name: 'tech-stack-evaluator',
    description: 'Technology stack evaluation: trade-off analysis, migration paths, TCO, and team capability assessment.',
    descriptionPt: 'Avaliação de stack tecnológica: análise de trade-offs, caminhos de migração, TCO e avaliação de capacidade da equipe.',
    tags: ['evaluation', 'trade-offs', 'tco'],
    domain: 'engineering-team',
    icon: '⚖️',
  },
  {
    name: 'self-improving-agent',
    description: 'Curates Claude Code auto-memory into durable project knowledge — extracts, promotes, and reviews memories.',
    descriptionPt: 'Curada a auto-memória do Claude Code em conhecimento durável de projeto — extrai, promove e revisa memórias.',
    tags: ['memory', 'knowledge', 'meta'],
    domain: 'engineering-team',
    icon: '🧬',
  },
  {
    name: 'snowflake-development',
    description: 'Snowflake SQL, data pipelines, Cortex AI integration, Snowpark Python, and performance optimization.',
    descriptionPt: 'SQL Snowflake, pipelines de dados, integração Cortex AI, Snowpark Python e otimização de performance.',
    tags: ['snowflake', 'sql', 'data-warehouse'],
    domain: 'engineering-team',
    icon: '❄️',
  },
  {
    name: 'senior-prompt-engineer',
    description: 'Senior prompt engineering: chain-of-thought, tool use, evaluation frameworks, and production hardening.',
    descriptionPt: 'Engenharia de prompts sênior: chain-of-thought, uso de ferramentas, frameworks de avaliação e hardening em produção.',
    tags: ['prompts', 'cot', 'evals'],
    domain: 'engineering-team',
    icon: '🎯',
  },
  {
    name: 'senior-computer-vision',
    description: 'Computer vision engineering: model selection, dataset curation, inference optimization, and deployment.',
    descriptionPt: 'Engenharia de visão computacional: seleção de modelos, curadoria de datasets, otimização de inferência e deploy.',
    tags: ['cv', 'vision', 'inference'],
    domain: 'engineering-team',
    icon: '👁️',
  },
  {
    name: 'incident-commander',
    description: 'Incident command coordination: communication templates, stakeholder updates, and resolution tracking.',
    descriptionPt: 'Coordenação de comando de incidentes: templates de comunicação, atualizações para stakeholders e rastreamento de resolução.',
    tags: ['command', 'communication', 'coordination'],
    domain: 'engineering-team',
    icon: '📡',
  },
  {
    name: 'senior-architect',
    description: 'Senior solutions architect: system design, architectural patterns, trade-off analysis, and ADRs.',
    descriptionPt: 'Arquiteto de soluções sênior: design de sistemas, padrões arquiteturais, análise de trade-offs e ADRs.',
    tags: ['architecture', 'patterns', 'adr'],
    domain: 'engineering-team',
    icon: '🏛️',
  },
  {
    name: 'database-designer',
    description: 'Database schema design, normalization, indexing strategy, query optimization, and migration planning.',
    descriptionPt: 'Design de schema de banco de dados, normalização, estratégia de indexação, otimização de queries e planejamento de migração.',
    tags: ['database', 'schema', 'indexing'],
    domain: 'engineering-team',
    icon: '🗃️',
  },
  {
    name: 'api-design-reviewer',
    description: 'Comprehensive REST API design review: versioning, error handling, pagination, and OpenAPI compliance.',
    descriptionPt: 'Revisão abrangente de design de API REST: versionamento, tratamento de erros, paginação e conformidade OpenAPI.',
    tags: ['rest', 'openapi', 'versioning'],
    domain: 'engineering-team',
    icon: '🔌',
  },
  {
    name: 'migration-architect',
    description: 'Database and system migration design: zero-downtime strategies, rollback plans, and validation.',
    descriptionPt: 'Design de migração de banco de dados e sistemas: estratégias zero-downtime, planos de rollback e validação.',
    tags: ['migration', 'zero-downtime', 'rollback'],
    domain: 'engineering-team',
    icon: '🚀',
  },
  {
    name: 'pr-review-expert',
    description: 'Pull request review expertise: comprehensive analysis, constructive feedback, and merge readiness.',
    descriptionPt: 'Expertise em revisão de pull requests: análise abrangente, feedback construtivo e prontidão para merge.',
    tags: ['pr', 'review', 'merge'],
    domain: 'engineering-team',
    icon: '👀',
  },
  {
    name: 'ci-cd-pipeline-builder',
    description: 'Generate pragmatic CI/CD pipelines for GitHub Actions, GitLab CI, and CircleCI with best practices.',
    descriptionPt: 'Gera pipelines CI/CD pragmáticos para GitHub Actions, GitLab CI e CircleCI com boas práticas.',
    tags: ['ci-cd', 'github-actions', 'gitlab'],
    domain: 'engineering-team',
    icon: '⚗️',
  },

  // ── AI Research ───────────────────────────────────────────
  {
    name: 'benchmark-analyzer',
    description: 'Interprets MMLU, HumanEval, MT-Bench, HELM, and GPQA scores. Flags misleading comparisons and ties results to your use case.',
    descriptionPt: 'Interpreta pontuações MMLU, HumanEval, MT-Bench, HELM e GPQA. Sinaliza comparações enganosas e vincula resultados ao seu caso de uso.',
    tags: ['mmlu', 'humaneval', 'mt-bench'],
    domain: 'ai-research',
    icon: '📊',
  },
  {
    name: 'model-eval',
    description: 'Designs custom evaluation frameworks: test set design, LLM-as-judge setup, automated pipelines, and regression detection.',
    descriptionPt: 'Projeta frameworks de avaliação customizados: design de test sets, configuração de LLM-as-judge, pipelines automatizados e detecção de regressão.',
    tags: ['test-set', 'llm-judge', 'regression'],
    domain: 'ai-research',
    icon: '🎯',
  },

  // ── AI Security ───────────────────────────────────────────
  {
    name: 'prompt-injection',
    description: 'Detects and hardens against prompt injection, jailbreaks, indirect injection via RAG, and system prompt extraction.',
    descriptionPt: 'Detecta e protege contra injeção de prompt, jailbreaks, injeção indireta via RAG e extração de system prompt.',
    tags: ['injection', 'jailbreak', 'hardening'],
    domain: 'ai-security',
    icon: '🛡️',
  },

  // ── Research ──────────────────────────────────────────────
  {
    name: 'pulse',
    description: 'Multi-source recency research across Reddit, HN, web, and Twitter — surfaces what\'s happening right now.',
    descriptionPt: 'Pesquisa de recência multi-fonte no Reddit, HN, web e Twitter — revela o que está acontecendo agora.',
    tags: ['trends', 'recency', 'multi-source'],
    domain: 'research',
    icon: '📡',
  },
  {
    name: 'litreview',
    description: 'Academic literature orientation and systematic review — gap analysis, key papers, and citation mapping.',
    descriptionPt: 'Orientação de literatura acadêmica e revisão sistemática — análise de lacunas, artigos-chave e mapeamento de citações.',
    tags: ['academic', 'papers', 'systematic'],
    domain: 'research',
    icon: '📰',
  },
  {
    name: 'dossier',
    description: 'Decision-grade entity research — hypothesis-tested dossier on companies, people, and organizations.',
    descriptionPt: 'Pesquisa de entidade de nível decisório — dossiê testado por hipóteses sobre empresas, pessoas e organizações.',
    tags: ['entity', 'decision', 'dossier'],
    domain: 'research',
    icon: '🗂️',
  },
  {
    name: 'patent',
    description: 'Patent prior-art and IP landscape intelligence — freedom to operate analysis and competitive mapping.',
    descriptionPt: 'Inteligência de prior-art de patentes e paisagem de PI — análise de liberdade de operação e mapeamento competitivo.',
    tags: ['patent', 'ip', 'prior-art'],
    domain: 'research',
    icon: '⚖️',
  },
  {
    name: 'research',
    description: 'Hybrid router and fallback orchestrator — intelligently routes queries to the right specialist skill.',
    descriptionPt: 'Roteador híbrido e orquestrador de fallback — roteia consultas de forma inteligente para a skill especialista correta.',
    tags: ['router', 'orchestrator', 'routing'],
    domain: 'research',
    icon: '🔀',
  },
  {
    name: 'syllabus',
    description: 'Supplementary reading list generation from course syllabi — structured learning path creation.',
    descriptionPt: 'Geração de lista de leitura complementar a partir de ementas de cursos — criação de trilha de aprendizagem estruturada.',
    tags: ['learning', 'curriculum', 'reading'],
    domain: 'research',
    icon: '📚',
  },
  {
    name: 'grants',
    description: 'NIH grant research for clinical researchers — funding opportunities, requirements, and application strategy.',
    descriptionPt: 'Pesquisa de grants NIH para pesquisadores clínicos — oportunidades de financiamento, requisitos e estratégia de candidatura.',
    tags: ['nih', 'grants', 'funding'],
    domain: 'research',
    icon: '💰',
  },
  {
    name: 'notebooklm',
    description: 'Google NotebookLM browser automation — content ingestion, source management, and insight extraction.',
    descriptionPt: 'Automação do Google NotebookLM no navegador — ingestão de conteúdo, gerenciamento de fontes e extração de insights.',
    tags: ['notebooklm', 'automation', 'google'],
    domain: 'research',
    icon: '📓',
  },

  // ── Research Ops ──────────────────────────────────────────
  {
    name: 'clinical-research',
    description: 'Prospective clinical study design — endpoints, sample size, power analysis, and phase-gating decisions.',
    descriptionPt: 'Design de estudo clínico prospectivo — endpoints, tamanho amostral, análise de poder e decisões de phase-gating.',
    tags: ['clinical', 'study-design', 'power'],
    domain: 'research-ops',
    icon: '🏥',
  },
  {
    name: 'market-research',
    description: 'Market sizing (TAM/SAM/SOM), survey design, customer segmentation, and competitive intelligence.',
    descriptionPt: 'Dimensionamento de mercado (TAM/SAM/SOM), design de pesquisa, segmentação de clientes e inteligência competitiva.',
    tags: ['tam', 'market-sizing', 'survey'],
    domain: 'research-ops',
    icon: '📈',
  },
  {
    name: 'product-research',
    description: 'Product and user research methodology — interview design, insight synthesis, and opportunity framing.',
    descriptionPt: 'Metodologia de pesquisa de produto e usuário — design de entrevistas, síntese de insights e enquadramento de oportunidades.',
    tags: ['user-research', 'interviews', 'insights'],
    domain: 'research-ops',
    icon: '🔍',
  },
  {
    name: 'research-finance',
    description: 'R&D program budgeting, burn and runway modeling, and capitalize-vs-expense routing decisions.',
    descriptionPt: 'Orçamento de programas P&D, modelagem de burn e runway e decisões de roteamento capitalizar-vs-despesa.',
    tags: ['r&d', 'budgeting', 'runway'],
    domain: 'research-ops',
    icon: '💼',
  },
  {
    name: 'research-ops-skills',
    description: 'Domain orchestrator that routes to clinical, market, product, or finance research specialists.',
    descriptionPt: 'Orquestrador de domínio que roteia para especialistas em pesquisa clínica, de mercado, de produto ou financeira.',
    tags: ['orchestrator', 'router', 'ops'],
    domain: 'research-ops',
    icon: '🗺️',
  },
]
